[build]
  command = "echo 'Static site deployment - no build required'"
  publish = "public"
  ignore = "exit 0"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/demo.html"
  status = 200

[[redirects]]
  from = "/deploy"
  to = "/deploy.html"
  status = 200

[[redirects]]
  from = "/partner"
  to = "/partner-demo.html"
  status = 200

[[redirects]]
  from = "/partner-demo"
  to = "/partner-demo.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"